- hosts: gitlab
  become: yes
  # pre_tasks:
  #   - name: Update apt cache
  #     apt: update_cache=true cache_valid_time=600
  #     when: ansible_os_family == 'Debian'
  #     changed_when: false
  roles:
    - role: robertdebock.gitlab
  post_tasks:
    - name: Read initial_root_password file
      slurp:
        src: /etc/gitlab/initial_root_password
      register: initial_root_password

    - name: Extract Password from variable initial_root_password
      set_fact:
        gitlab_password: "{{ initial_root_password['content'] | b64decode | regex_search('Password: (.+)', '\\1') | first }}"

    - name: Print gitlab password
      debug:
        var: gitlab_password
